// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rx7.gltf 
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mazda-rx-7-1992-wwwvecarzcom-4a7d2c43737e4951bbe8b155aa5d477e
Title: Mazda RX-7 1992 | www.vecarz.com
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

import { Annotation } from 'components';
import { AnnotationData as AnnotationModel } from 'models';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rx7/rx7.gltf');

  // Body color
  materials.material_0.color = new THREE.Color(props.color);

  // Brake calipers color
  materials.material_13.color = new THREE.Color(props.brakeCaliperColor);

  // Seat colors
  materials.material_26.color = new THREE.Color(props.seatColor);
  materials.material_27.color = new THREE.Color(props.seatColor);

  // Wheel color
  materials.material_16.color = new THREE.Color(props.wheelColor);

  // Windows
  materials.material_28.color = new THREE.Color(props.windowTint);

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material_0}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material_1}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material_2}
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.material_3}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.material_4}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.material_5}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.material_6}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.material_7}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.material_8}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.material_9}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.material_10}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials.material_11}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials.material_12}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials.material_13}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.material_14}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.material_15}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials.material_16}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials.material_17}
        />
        <mesh
          geometry={nodes.Object_43.geometry}
          material={materials.material_18}
        />
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.material_19}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.material_20}
        />
        <mesh
          geometry={nodes.Object_49.geometry}
          material={materials.material_21}
        />
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials.material_22}
        />
        <mesh
          geometry={nodes.Object_53.geometry}
          material={materials.material_23}
        />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.material_24}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials.material_25}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.material_26}
        />
        <mesh
          geometry={nodes.Object_61.geometry}
          material={materials.material_27}
        />
        <mesh
          geometry={nodes.Object_63.geometry}
          material={materials.material_28}
        />
        <mesh
          geometry={nodes.Object_65.geometry}
          material={materials.material_29}
        />
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials.material_30}
        />
        {props.annotations.map((props, index) => {
          return <Annotation key={index} {...props} />;
        })}
      </group>
    </group>
  );
}

useGLTF.preload('/rx7/rx7.gltf');
