// @ts-nocheck

/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
Command: npx gltfjsx@6.5.3 rx7.gltf 
Author: vecarz (https://sketchfab.com/heynic)
License: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
Source: https://sketchfab.com/3d-models/mazda-rx-7-1992-wwwvecarzcom-4a7d2c43737e4951bbe8b155aa5d477e
Title: Mazda RX-7 1992 | www.vecarz.com
*/

import React from 'react';
import { useGLTF } from '@react-three/drei';
import * as THREE from 'three';

import { Annotation } from 'components';
import { AnnotationData as AnnotationModel } from 'models';
import { useAppSelector } from 'store';

export default function Model(props) {
  const { nodes, materials } = useGLTF('/rx7/rx7.gltf');
  const { activeAnnotationIndex, showAnnotations } = useAppSelector(
    ({ controlsSlice }) => controlsSlice
  );

  // Body color
  materials.material_0.color = new THREE.Color(props.color);

  // Brake calipers color
  materials.material_13.color = new THREE.Color(props.brakeCaliperColor);

  // Seat colors
  materials.material_26.color = new THREE.Color(props.seatColor);
  materials.material_27.color = new THREE.Color(props.seatColor);

  // Wheel color
  materials.material_16.color = new THREE.Color(props.wheelColor);

  // Windows
  materials.material_28.color = new THREE.Color(props.windowTint);

  const getWheelAnnotationPosition = () => {
    if (!showAnnotations) {
      return [0, 0, 0];
    }

    if (activeAnnotationIndex === 3) {
      return [2, 0, 0];
    }

    if (activeAnnotationIndex === 4) {
      return [1000, 0, 0];
    }
  };

  const getSuspensionHeight = () => {
    if (!props.suspensionHeight) {
      return [0, 0, 0];
    }

    return [0, 0, props.suspensionHeight];
  };

  const wheelAnnotationPosition = getWheelAnnotationPosition();

  const loweredSuspension = getSuspensionHeight();

  return (
    <group {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <mesh
          geometry={nodes.Object_7.geometry}
          material={materials.material_0}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_9.geometry}
          material={materials.material_1}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_11.geometry}
          material={materials.material_2}
          // position={loweredSuspension}
          // Wheel nuts
        />
        <mesh
          geometry={nodes.Object_13.geometry}
          material={materials.material_3}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_15.geometry}
          material={materials.material_4}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_17.geometry}
          material={materials.material_5}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_19.geometry}
          material={materials.material_6}
        />
        <mesh
          geometry={nodes.Object_21.geometry}
          material={materials.material_7}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_23.geometry}
          material={materials.material_8}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_25.geometry}
          material={materials.material_9}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_27.geometry}
          material={materials.material_10}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_29.geometry}
          material={materials.material_11}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_31.geometry}
          material={materials.material_12}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_33.geometry}
          material={materials.material_13}
        />
        <mesh
          geometry={nodes.Object_35.geometry}
          material={materials.material_14}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_37.geometry}
          material={materials.material_15}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_39.geometry}
          material={materials.material_16}
          position={wheelAnnotationPosition}
        />
        <mesh
          geometry={nodes.Object_41.geometry}
          material={materials.material_17}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_43.geometry}
          material={materials.material_18}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_45.geometry}
          material={materials.material_19}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_47.geometry}
          material={materials.material_20}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_49.geometry}
          material={materials.material_21}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_51.geometry}
          material={materials.material_22}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_53.geometry}
          material={materials.material_23}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_55.geometry}
          material={materials.material_24}
          position={wheelAnnotationPosition}
        />
        <mesh
          geometry={nodes.Object_57.geometry}
          material={materials.material_25}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_59.geometry}
          material={materials.material_26}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_61.geometry}
          material={materials.material_27}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_63.geometry}
          material={materials.material_28}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_65.geometry}
          material={materials.material_29}
          position={loweredSuspension}
        />
        <mesh
          geometry={nodes.Object_67.geometry}
          material={materials.material_30}
          position={loweredSuspension}
        />
        {props.annotations.map((props, index) => {
          return <Annotation key={index} {...props} />;
        })}
      </group>
    </group>
  );
}

useGLTF.preload('/rx7/rx7.gltf');
